title: "Blog de Analítica Avanzada - Maria Fernanda"
description: "Análisis de Flujo de Datos Simulado con Spark"
theme: jekyll-theme-cayman
baseurl: "/maria_herazo_trabajo-tercer_corte"
url: "https://MariaFer2006.github.io"
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - generate_graphs.py
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .gitignore